[Breaking Change] Enforces use of kms key and restricts on default
UKHomeOffice/acp-tf-s3 pull request #29
Opened 2018-04-23 08:58 UTC by AwkwardBen

Fix to the following bau issue https://github.com/UKHomeOffice/application-container-platform-bau/issues/3056

2018-04-24 11:56 UTC, tasharnvb reviewed
You could remove the other condition too, since this change will force `x-amz-server-side-encryption` to be `aws:kms` anyway.

2018-05-22 10:54 UTC, KashifSaadat commented on policy.tf
> -      test     = "StringNotEquals"
Run `terraform fmt`, it will align the values here and add the spacing back in

2018-05-22 10:55 UTC, KashifSaadat commented on policy.tf
> +      variable = "s3:x-amz-server-side-encryption-aws-kms-key-id"
Does the variable here support the alias for the KMS Key? Can you test and validate? The KMS key alias should also be added in the list of values below

2018-05-22 10:55 UTC, KashifSaadat commented on policy.tf
> +      values = ["${aws_kms_key.s3_bucket_kms_key.arn}"]
Same as above in reference to the KMS alias

2018-05-22 10:55 UTC, KashifSaadat commented on policy.tf
> +
Some rogue spaces here!

2018-05-22 10:56 UTC, KashifSaadat requested changes
Added some comments, otherwise LG (and breaking change, so bump to v0.X)

2018-05-22 10:56 UTC, marcinc reviewed
Terraform will most likely complain about the formatting so... `terraform fmt`.

2018-05-22 11:04 UTC, KashifSaadat commented on policy.tf
> +      variable = "s3:x-amz-server-side-encryption-aws-kms-key-id"
The documentation suggests that use of the alias isn't supported with this behaviour. Still worth testing, otherwise nothing to change here.

2018-05-22 13:43 UTC, KashifSaadat approved these changes
LG, tag as breaking change

2018-05-22 15:57 UTC, merged