Added non-mandatory kms key setup with versioning and mfa features
UKHomeOffice/acp-tf-s3 pull request #6
Opened 2017-08-24 13:54 UTC by AwkwardBen

2017-08-24 14:39 UTC, oyelekci approved these changes
LGTM

2017-08-24 14:43 UTC, jaykeshur commented
A few things:
- The s3 policy doesn't include being able to use the kms-id
- The s3 policy should include server side encryption using that key only.
- you need to create a user to do all of this

2017-08-24 14:44 UTC, jaykeshur requested changes
notes added

2017-08-24 15:08 UTC, marcinc commented on README.md
> +| mfa_delete_enabled | If mfa is need for delete for s3 bucket | false | no |
If you could reword that a little bit that would be good.

2017-08-25 08:22 UTC, jaykeshur commented on main.tf
> +  policy =
should this be empty?

2017-08-25 09:14 UTC, jaykeshur approved these changes

2017-08-25 09:19 UTC, merged